### ISSUE TITLE
ramen client exit failure if confserver is not started.

### ISSUE THREAD

**Issue by darlentar** [rixed/ramen#1171]
```
[dbihel@Host-001 ramen]$ ./src/ramen choreographer --confserver localhost:29340 --stdout
17h38m57: Starting choreographer v4.4.2
^C17h38m58:(E) Authentication: Not established: Stdlib.Pervasives.Exit
^CFatal error: exception Unix.Unix_error(Unix.EINTR, "zmq_ctx_term", "")

```

**Comment by rixed** [comment]
It's actually a feature (one of the few we get from 0mq) not a bug.
I'm assuming the problem is rather that the logs were misleading. Indeed, it would have been better to log that it's waiting for the confserver, and then that it's starting. Not sure if it's worth the 2 additional info log lines though.
Please reopen (with a better name) if you feel otherwise.
