### ISSUE TITLE
ramen http api is slow when multiple requests are done on the same socket

### ISSUE THREAD

**Issue by darlentar** [rixed/ramen#1268]
use
```
root@shuttle:/home # time curl -X POST http://localhost:29380/api/v1 -d '{"method":"version", "id":1}'  --next   -X POST http://localhost:29380/api/v1 -d '{"method":"version", "id":1}'
{"id":1,"result":"v4.5.6"}{"id":1,"result":"v4.5.6"}
real    0m8,397s
user    0m0,004s
sys     0m0,004s
```

**Comment by rixed** [comment]
Thank you for the repro case.
strace reveals that on that machine a lot of time on that machine is spent (un)serializing the http response time stat file in `ramen/binocle/v0.12.0/http_resp_time`. For some reason, the histogram stored there is huge, with many times the same bucket.
The bug is therefore likely to be in the binocle histogram bucket merge ; my money on a float equality test.

**Comment by rixed** [comment]
Actually, the bucket merge code looks alright, but the serialization using PPP is the issue, as floats are written with string_of_float, but we happen to have plenty of very short resp times that are <10^-11s and very close to each others:

```ocaml
# let f = float_of_string "0x1.fffffffffffffp-12";;
val f : float = 0.000488281249999999946
# string_of_float f;;
- : string = "0.00048828125"
```
I can think of several solutions to this problem:
1- implement a float printer that displays the minium required amount of decimal places, but that's not as easy as it sounds;
2- serialize in binary form, with the advantage of being faster but is a bit annoying for ops;
3- try a few decimal places as ocaml toplevel does, to make sure float_of_string can read the value correctly.

Although slower, I'll go with solution 3 for now, as changing the serialization format requires more consideration.

To help recover the currently broken stat files, binocle could merge the buckets of histogram values after the file is unserialized.
